IF(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    SET(PLATFORM_LIBS
            X11
    )
ELSEIF(CMAKE_SYSTEM_NAME STREQUAL "Windows")
    SET(PLATFORM_LIBS

    )
ELSEIF(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    SET(PLATFORM_LIBS

    )
ENDIF()
